services:
  - type: web
    name: cloudvote-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: cloudvote
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
